spring:
  application:
    name: SpringLogging
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:log4j2.xml
